### ISSUE TITLE
(improve) VFX - Fight Zone

### ISSUE THREAD

**Issue by s1n-c0s** [s1n-c0s/UNDERLINE#125]
![image](https://github.com/s1n-c0s/UNDERLINE/assets/99553613/390a9b03-b1fa-40c6-a129-e4150dfef9d1)
![image](https://github.com/s1n-c0s/UNDERLINE/assets/99553613/165aa7d7-82ca-4238-8c34-3f85610948c7)

![Image](https://github.com/s1n-c0s/UNDERLINE/assets/99553613/5cae3ffc-d42b-4766-bebe-1778926b3a1d)

# https://youtu.be/yexoBhUsJ1k?si=T--N1qFpf1k2TRsp

**Comment by s1n-c0s** [comment]
![Image](https://github.com/s1n-c0s/UNDERLINE/assets/99553613/4442ff42-2969-4c67-bd9a-c67f3d088fe7)



## [ATKZone.pdf](https://github.com/user-attachments/files/15826135/ATKZone.pdf)

**Comment by s1n-c0s** [comment]
# It has problem Don't see @takemiethere 

![Image](https://github.com/s1n-c0s/UNDERLINE/assets/99553613/1fc8b15a-a014-40ed-8aa1-db70b5f5a48c)



![Image](https://github.com/s1n-c0s/UNDERLINE/assets/99553613/75a829c6-cf2c-400d-972c-b4d06e3fe75d)


![Image](https://github.com/s1n-c0s/UNDERLINE/assets/99553613/0573d103-fb4a-4836-a63b-f1ccf4942f43)



![Image](https://github.com/s1n-c0s/UNDERLINE/assets/99553613/b9eef612-404b-4764-8ef7-15179082bf99)

**Comment by takemiethere** [comment]
> # It's has problem Don't see @takemiethere 
> 
> ![Image](https://github.com/s1n-c0s/UNDERLINE/assets/99553613/1fc8b15a-a014-40ed-8aa1-db70b5f5a48c)
> 
> 
> 
> ![Image](https://github.com/s1n-c0s/UNDERLINE/assets/99553613/75a829c6-cf2c-400d-972c-b4d06e3fe75d)
> 
> 
> ![Image](https://github.com/s1n-c0s/UNDERLINE/assets/99553613/0573d103-fb4a-4836-a63b-f1ccf4942f43)
> 
> 
> 
> ![Image](https://github.com/s1n-c0s/UNDERLINE/assets/99553613/b9eef612-404b-4764-8ef7-15179082bf99)
> 
> 
> 

That's bad, I will fix it, I think we have to make a new one asap.

**Comment by s1n-c0s** [comment]
![Image](https://github.com/user-attachments/assets/66cdd11e-c63c-4e61-a3eb-30fc54af290d)
