### ISSUE TITLE
(improve) VFX - Trigger Block dmg

### ISSUE THREAD

**Issue by s1n-c0s** [s1n-c0s/UNDERLINE#194]
## Keyword: Braum
https://youtu.be/NRukOew2TIA?si=D0au57jPZ53Jf1dD&t=107

![Image](https://github.com/s1n-c0s/UNDERLINE/assets/99553613/29bac23b-f01f-46b3-946d-5e360283c561)

![Image](https://github.com/s1n-c0s/UNDERLINE/assets/99553613/2873732f-804e-4feb-b6a5-8c54178a3431)

**Comment by s1n-c0s** [comment]
# [Block.pdf](https://github.com/user-attachments/files/15825724/Block.pdf)

**Comment by s1n-c0s** [comment]
![Image](https://github.com/s1n-c0s/UNDERLINE/assets/99553613/06bd1760-784d-450a-a8d4-63da598339e3)

@takemiethere it's okay?

**Comment by takemiethere** [comment]
> 
> 
> ![Image](https://github.com/s1n-c0s/UNDERLINE/assets/99553613/06bd1760-784d-450a-a8d4-63da598339e3)
> 
> @takemiethere it's okay?

It's okay but in my opinion I think it's a little bit big, I prefer smaller.

**Comment by s1n-c0s** [comment]
![Image](https://github.com/s1n-c0s/UNDERLINE/assets/99553613/75de289d-2c5b-41d5-aabb-ebb4f34a2485)

**Comment by s1n-c0s** [comment]
> It's okay but in my opinion I think it's a little bit big, I prefer smaller.

I think it won't see when SizeUp skill active Enemy will overlap it.
this vfx that spawn as same size if need to change size to spawn when enemy not active skill (normal size) or active skill (bigger size)
need to create new function to handle it
