### ISSUE TITLE
(add) VFX - Shadow Player On Spawn อัญเชิญ

### ISSUE THREAD

**Issue by s1n-c0s** [s1n-c0s/UNDERLINE#257]
![Image](https://github.com/s1n-c0s/UNDERLINE/assets/99553613/674c7243-4634-4410-aa1a-27e8fe741ac9)

**Comment by takemiethere** [comment]
![Image](https://github.com/user-attachments/assets/ac0acc05-9a94-4fa7-b7d9-890dffc7a20f)

**Comment by s1n-c0s** [comment]
https://github.com/user-attachments/assets/80cdf7f0-5420-400f-8cf9-b3e10528e672
